### ISSUE TITLE
Weird type of command argument

### ISSUE THREAD

**Issue by Mcbeany** [mcbeany-pm-pl/BetterMinion#1]
![image](https://user-images.githubusercontent.com/77101686/133079430-4ba089a2-0448-455a-902a-9cb9c0d0413e.png)

**Comment by llPushkarSinghll** [comment]
Better make ui rather than command

**Comment by MrNinja008** [comment]
> Better make ui rather than command

Nah then you cant able to give minions via cmds in crates and stuffs

**Comment by llPushkarSinghll** [comment]
> > Better make ui rather than command
> 
> Nah then you cant able to give minions via cmds in crates and stuffs

Hmm ok

**Comment by Mcbeany** [comment]
switch to Paroxity's Commando (`master` branch only)

**Comment by Mcbeany** [comment]
Fixed
