### ISSUE TITLE
Compacter Issue

### ISSUE THREAD

**Issue by BhawaniSinghRaj** [mcbeany-pm-pl/BetterMinion#15]
Compacter Not Working.

When New Update Come?

**Comment by Mcbeany** [comment]
Plugin by default only supports some compactable target of minion, but you can still edit it in `compacts.json`
I need to know exactly what you need

**Comment by BhawaniSinghRaj** [comment]
> Plugin by default only supports some compactable target of minion, but you can still edit it in `compacts.json` I need to know exactly what you need

Compacter Not Compress Anything I See Compects.json But There Is Diamond:0:9 = Diamond_Block But This Not Working 

Plz Fix This Soon And Realease New Update Fast

**Comment by Mcbeany** [comment]
Minion's inventory may not have enough space to compress items to blocks

**Comment by BhawaniSinghRaj** [comment]
> Minion's inventory may not have enough space to compress items to blocks

I Upgraded Minion To Max Level And Try This Again Not Working I Minion Inventory Is Full With Iron But Not Iron Block Fix This Problem And Try To Add Custom Upgrade Like We Can Upgrade Cobblestone Minion With Cobblestone And Lapis Minion With Lapis Lazuli.

**Comment by KingboiDre** [comment]
English-

**Comment by Mcbeany** [comment]
"not working" is not a valid problem
Can you show me a video of it?

**Comment by KingboiDre** [comment]
Hehe
