### ISSUE TITLE
not staring and crashing server 

### ISSUE THREAD

**Issue by NOOBHH** [mcbeany-pm-pl/BetterMinion#27]
Error: "Class "Mcbeany\BetterMinion\libs\CortexPE\Commando\PacketHooker" not found" (EXCEPTION) in "plugins/BetterMinion_dev-133.phar/src/BetterMinion" at line 23
--- Stack trace ---
  #0 pmsrc/src/plugin/PluginBase(137): Mcbeany\BetterMinion\BetterMinion->onEnable()
  #1 pmsrc/src/plugin/PluginManager(437): pocketmine\plugin\PluginBase->onEnableStateChange(true)
  #2 pmsrc/src/Server(1385): pocketmine\plugin\PluginManager->enablePlugin(object Mcbeany\BetterMinion\BetterMinion#24952)
  #3 pmsrc/src/Server(1011): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#24901)
  #4 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
  #5 pmsrc/src/PocketMine(327): pocketmine\server()
  #6 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---
[04:53:52.586] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[04:53:52.592] [Server thread/EMERGENCY]: Please upload the "/home/container/crashdumps/Sun_Feb_27-04.53.52-UTC_2022.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
[04:53:53.320] [Server thread/EMERGENCY]: The crash dump has been automatically submitted to the Crash Archive. You can view it on https://crash.pmmp.io/view/6039798 or use the ID #6039798.
[04:53:53.320] [Server thread/EMERGENCY]: Forcing server shutdown

ERROR SEE THIS AND PLEASE FIX THIS

**Comment by NOOBHH** [comment]
I AM USING POCKETMINE LATEST VERSION PLS FIX API 4

**Comment by BhawaniSinghRaj** [comment]
> Error: "Class "Mcbeany\BetterMinion\libs\CortexPE\Commando\PacketHooker" not found" (EXCEPTION) in "plugins/BetterMinion_dev-133.phar/src/BetterMinion" at line 23 --- Stack trace --- #0 pmsrc/src/plugin/PluginBase(137): Mcbeany\BetterMinion\BetterMinion->onEnable() #1 pmsrc/src/plugin/PluginManager(437): pocketmine\plugin\PluginBase->onEnableStateChange(true) #2 pmsrc/src/Server(1385): pocketmine\plugin\PluginManager->enablePlugin(object Mcbeany\BetterMinion\BetterMinion#24952) #3 pmsrc/src/Server(1011): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#24901) #4 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/) #5 pmsrc/src/PocketMine(327): pocketmine\server() #6 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php) --- End of exception information --- [04:53:52.586] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump [04:53:52.592] [Server thread/EMERGENCY]: Please upload the "/home/container/crashdumps/Sun_Feb_27-04.53.52-UTC_2022.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can. [04:53:53.320] [Server thread/EMERGENCY]: The crash dump has been automatically submitted to the Crash Archive. You can view it on https://crash.pmmp.io/view/6039798 or use the ID #6039798. [04:53:53.320] [Server thread/EMERGENCY]: Forcing server shutdown
> 
> ERROR SEE THIS AND PLEASE FIX THIS

Use Commando And InvMenu Virion!

**Comment by LuciferVerma** [comment]
![IMG_20220318_081256](https://user-images.githubusercontent.com/68379472/158928834-5f0859ff-5463-4c16-9717-201610ab9b41.jpg)
Same error
