### ISSUE TITLE
Plugin library not found

### ISSUE THREAD

**Issue by LuciferVerma** [mcbeany-pm-pl/BetterMinion#32]
![IMG_20220318_081256](https://user-images.githubusercontent.com/68379472/158928834-5f0859ff-5463-4c16-9717-201610ab9b41.jpg)
Same error

_Originally posted by @LuciferVerma in https://github.com/mcbeany-pm-pl/BetterMinion/issues/27#issuecomment-1071977857_

**Comment by LuciferVerma** [comment]
As you can see some people are getting same error as mine, and I'm quite confused now about how to make it work, like do i have to upload virons, or is it in-built, if we have to upload virons then which ones, cause i have tried uploading virons and it didn't work, so it will be very helpful if you provide a detailed information on how to use it or make a quick tutorial and it will be better if you also provide virons, in-case we have to use that to

**Comment by Mcbeany** [comment]
where did you install this plugin?

**Comment by LuciferVerma** [comment]
From here :- https://poggit.pmmp.io/ci/mcbeany-pm-pl/BetterMinion

**Comment by Mcbeany** [comment]
We'll fix this as soon as we can

**Comment by Mcbeany** [comment]
Fixed
